import { Card, CardType, Rarity } from "@/cards/Card"

const createCard = (name: string, rarity: Rarity, type: CardType): Card => ({ name, rarity, type })

const allCards: Card[] = [
  createCard("Alakazam", "Holo Rare", "Pokémon"),
  createCard("Blastoise", "Holo Rare", "Pokémon"),
  createCard("Chansey", "Holo Rare", "Pokémon"),
  createCard("Charizard", "Holo Rare", "Pokémon"),
  createCard("Clefairy", "Holo Rare", "Pokémon"),
  createCard("Gyarados", "Holo Rare", "Pokémon"),
  createCard("Hitmonchan", "Holo Rare", "Pokémon"),
  createCard("Machamp", "Holo Rare", "Pokémon"),
  createCard("Magneton", "Holo Rare", "Pokémon"),
  createCard("Mewtwo", "Holo Rare", "Pokémon"),
  createCard("Nidoking", "Holo Rare", "Pokémon"),
  createCard("Ninetales", "Holo Rare", "Pokémon"),
  createCard("Poliwrath", "Holo Rare", "Pokémon"),
  createCard("Raichu", "Holo Rare", "Pokémon"),
  createCard("Venusaur", "Holo Rare", "Pokémon"),
  createCard("Zapdos", "Holo Rare", "Pokémon"),
  createCard("Beedrill", "Rare", "Pokémon"),
  createCard("Dragonair", "Rare", "Pokémon"),
  createCard("Dugtrio", "Rare", "Pokémon"),
  createCard("Electabuzz", "Rare", "Pokémon"),
  createCard("Electrode", "Rare", "Pokémon"),
  createCard("Pidgeotto", "Rare", "Pokémon"),
  createCard("Arcanine", "Uncommon", "Pokémon"),
  createCard("Charmeleon", "Uncommon", "Pokémon"),
  createCard("Dewgong", "Uncommon", "Pokémon"),
  createCard("Dratini", "Uncommon", "Pokémon"),
  createCard("Farfetch'd", "Uncommon", "Pokémon"),
  createCard("Growlithe", "Uncommon", "Pokémon"),
  createCard("Haunter", "Uncommon", "Pokémon"),
  createCard("Ivysaur", "Uncommon", "Pokémon"),
  createCard("Jynx", "Uncommon", "Pokémon"),
  createCard("Kadabra", "Uncommon", "Pokémon"),
  createCard("Kakuna", "Uncommon", "Pokémon"),
  createCard("Machoke", "Uncommon", "Pokémon"),
  createCard("Magikarp", "Uncommon", "Pokémon"),
  createCard("Magmar", "Uncommon", "Pokémon"),
  createCard("Nidorino", "Uncommon", "Pokémon"),
  createCard("Poliwhirl", "Uncommon", "Pokémon"),
  createCard("Porygon", "Uncommon", "Pokémon"),
  createCard("Raticate", "Uncommon", "Pokémon"),
  createCard("Seel", "Uncommon", "Pokémon"),
  createCard("Wartortle", "Uncommon", "Pokémon"),
  createCard("Abra", "Common", "Pokémon"),
  createCard("Bulbasaur", "Common", "Pokémon"),
  createCard("Caterpie", "Common", "Pokémon"),
  createCard("Charmander", "Common", "Pokémon"),
  createCard("Diglett", "Common", "Pokémon"),
  createCard("Doduo", "Common", "Pokémon"),
  createCard("Drowzee", "Common", "Pokémon"),
  createCard("Gastly", "Common", "Pokémon"),
  createCard("Koffing", "Common", "Pokémon"),
  createCard("Machop", "Common", "Pokémon"),
  createCard("Magnemite", "Common", "Pokémon"),
  createCard("Metapod", "Common", "Pokémon"),
  createCard("Nidoran♂", "Common", "Pokémon"),
  createCard("Onix", "Common", "Pokémon"),
  createCard("Pidgey", "Common", "Pokémon"),
  createCard("Pikachu", "Common", "Pokémon"),
  createCard("Poliwag", "Common", "Pokémon"),
  createCard("Ponyta", "Common", "Pokémon"),
  createCard("Rattata", "Common", "Pokémon"),
  createCard("Sandshrew", "Common", "Pokémon"),
  createCard("Squirtle", "Common", "Pokémon"),
  createCard("Starmie", "Common", "Pokémon"),
  createCard("Staryu", "Common", "Pokémon"),
  createCard("Tangela", "Common", "Pokémon"),
  createCard("Voltorb", "Common", "Pokémon"),
  createCard("Vulpix", "Common", "Pokémon"),
  createCard("Weedle", "Common", "Pokémon"),
  createCard("Professor Oak", "Uncommon", "Trainer"),
  createCard("Bill", "Common", "Trainer"),
  createCard("Energy Removal", "Common", "Trainer"),
  createCard("Gust of Wind", "Common", "Trainer"),
  createCard("Potion", "Common", "Trainer"),
  createCard("Super Potion", "Uncommon", "Trainer"),
  createCard("Switch", "Common", "Trainer"),
  createCard("Full Heal", "Uncommon", "Trainer"),
  createCard("Revive", "Uncommon", "Trainer"),
  createCard("Computer Search", "Rare", "Trainer"),
  createCard("Devolution Spray", "Rare", "Trainer"),
  createCard("Item Finder", "Rare", "Trainer"),
  createCard("Lass", "Rare", "Trainer"),
  createCard("Pokémon Breeder", "Rare", "Trainer"),
  createCard("Pokémon Trader", "Rare", "Trainer"),
  createCard("Defender", "Uncommon", "Trainer"),
  createCard("PlusPower", "Uncommon", "Trainer"),
  createCard("Pokédex", "Uncommon", "Trainer"),
  createCard("Maintenance", "Uncommon", "Trainer"),
  createCard("Double Colorless Energy", "Rare", "Energy"),
  createCard("Fighting Energy", "Common", "Energy"),
  createCard("Fire Energy", "Common", "Energy"),
  createCard("Grass Energy", "Common", "Energy"),
  createCard("Lightning Energy", "Common", "Energy"),
  createCard("Psychic Energy", "Common", "Energy"),
  createCard("Water Energy", "Common", "Energy"),
]

export const getRandomCard = (): Card => {
  const cardIndex = Math.floor(Math.random() * allCards.length)
  return allCards[cardIndex]
}

export const getRandomCards = (amount: number): Card[] => {
  const cards: Card[] = []

  for (let i = 0; i < amount; i++) {
    cards.push(getRandomCard())
  }

  return cards
}
